name: valgrind
on: [push, pull_request]

jobs:
  valgrind:
    runs-on: ubuntu-latest
    name: valgrind-check
    steps:
    - uses: actions/checkout@v2
    - name: leak-check
      uses: solareenlo/42valgrind-action@v1.0.3
      with:
        flags: 'sh test_valgrind.sh'
